# .github/workflows/run-tests.yml
name: Run Vitest Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run Vitest with coverage
        run: npm run test:ci

      - name: Check test coverage minimum (90%)
        run: |
          if [ ! -f coverage/coverage-summary.json ]; then
            echo "❌ coverage-summary.json not found."
            exit 1
          fi
          COVERAGE=$(node -e '
            const fs = require("fs");
            const data = JSON.parse(fs.readFileSync("coverage/coverage-summary.json", "utf8"));
            const statements = data.total?.statements?.pct;
            if (statements == null) {
              console.error("❌ No statements coverage found.");
              process.exit(1);
            }
            console.log(`✅ Test Coverage: ${statements}%`);
            if (statements < 90) {
              console.error(`❌ Coverage (${statements}%) is below 90%`);
              process.exit(1);
            }
          ')
