# .github/workflows/run-tests.yml
name: Run Vitest Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run Vitest with coverage
        run: npm run test:ci

      - name: Check test coverage minimum (90%)
        run: |
          node -e '
            const fs = require("fs");
            const path = "./coverage/coverage-final.json";
            if (!fs.existsSync(path)) {
              console.error("❌ coverage-final.json not found.");
              process.exit(1);
            }
            const data = JSON.parse(fs.readFileSync(path, "utf8"));
            const files = Object.values(data).filter(f => f?.statements?.pct != null);
            if (!files.length) {
              console.error("❌ No coverage data found in coverage-final.json");
              process.exit(1);
            }
            const avg = files.reduce((sum, f) => sum + f.statements.pct, 0) / files.length;
            console.log(`✅ Test Coverage: ${avg.toFixed(2)}%`);
            if (avg < 90) {
              console.error(`❌ Coverage (${avg.toFixed(2)}%) is below 90%`);
              process.exit(1);
            }
          '
