# .github/workflows/run-tests.yml
name: Run Vitest Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run Vitest with coverage
        run: npm run test:ci

      - name: Check test coverage minimum (90%)
        run: |
          COVERAGE=$(jq '.total.statements.pct' coverage/coverage-summary.json)
          echo "Test Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 90" | bc -l) )); then
            echo "Coverage ($COVERAGE%) is below 90%. Failing the job."
            exit 1
          fi
